### PR TITLE
Tweaks for PyPI release

### PR DESCRIPTION
**Pull request by patrick-kidger**
#100 has prompted me to try and sort out PyPI.

I've provisionally already pushed a release to PyPI; I think everything seems to be working fine. @lxuechen if you're happy with this state of affairs then this PR will update the documentation.

### CODE REVIEW

**Comment by patrick-kidger** [comment]
CC @Zymrael -- a provisional (manual rather than automated) torchsde release is now available on PyPI.

**Comment by patrick-kidger** [comment]
Also Chen, lmk what your PyPI username is so I can add you as an owner over there. I'm expecting it's lxuechen like everywhere else, but I'm just making sure.

**Comment by dhirschfeld** [comment]
> a provisional torchsde release is now available on PyPI.

It would be great if the GitHub source could also be tagged so that it's clear what version of the code is being installed.

**Comment by lxuechen** [comment]
Thanks for the updates! I'll follow up quickly on this tomorrow.

**Review by lxuechen — APPROVED** [review]

**Comment by lxuechen** [comment]
> Also Chen, lmk what your PyPI username is so I can add you as an owner over there. I'm expecting it's lxuechen like everywhere else, but I'm just making sure.

Yes, the username is `lxuechen`.

**Comment by patrick-kidger** [comment]
@lxuechen have now added you on PyPI.

**Comment by patrick-kidger** [comment]
> It would be great if the GitHub source could also be tagged so that it's clear what version of the code is being installed.

Yep, we'll create a v0.2.5 release on GitHub at some point shortly, which will correspond to the version available on PyPI.

**Pull request merged**
