### PR TITLE
bump version number

### PR DESCRIPTION
**Pull request by vladmandic**
bumps version number of torchsde package so it can be used to create a new release and published to pypi.
see #131 for details

### CODE REVIEW

**Comment by patrick-kidger** [comment]
The failing tests here are what I was referring to over in #131 btw; I think the CI needs updating.

**Comment by vladmandic** [comment]
> The failing tests here are what I was referring to over in #131 btw; I think the CI needs updating.

yup. but updating CI is non-trivial since it has a lot of obsolete dependencies (not to mention python 3.6 itself).
and you said yourself this is no longer an actively maintained package.

so we can either:
- disable CI and do a release and package push
- agree this will never get done - and cause quite a stir once `pip` upgrades this from **warning** to actual **error** (as it promises to do) since there are many upstream packages relying on this.

**Comment by patrick-kidger** [comment]
I think the options here are:
- update the CI; do a release.
- status quo: things stay broken.

It has been very cool to see how much usage torchsde has received downstream! Hopefully this suggests that someone will be willing to step up to the plate and do the work to update the CI. :) (If anyone else comes across this and wants to do the work, go for it! I'm very happy to merge fixes.)

Absent that, the main other recommendation I have for you is to use [Diffrax](https://github.com/patrick-kidger/diffrax) instead. This is maintained and actively developed. (Why the second library? Diffrax uses the lessons we learnt building torchsde -- which was only ever a research project -- to produce something suitable for use in production. So Diffrax is faster, generally more featureful, etc.)

**Comment by patrick-kidger** [comment]
Great questions!

1) Is it easy to refactor?

I find refactoring to be straightforward. As someone who already knows both frameworks: for a "serious" model like a u-net, transformer, diffusion, whatever, it usually takes me about a day. Everyone's settled on the same basic set of primitives: linear layers, conv layers, and so on.

2) Are there existing implementations of SD?

I don't know of specifically a public SD implementation. It wouldn't be terribly hard, though, and we could definitely publicise that as an example if someone takes the time to implement it.

As a reference point though, there is a [general diffusion implementation here].(https://docs.kidger.site/equinox/examples/score_based_diffusion/)

**Comment by vladmandic** [comment]
> > Absent that, the main other recommendation I have for you is to use [Diffrax](https://github.com/patrick-kidger/diffrax) instead.
> 
> any easy way to refactor from torchsde to diffrax? Have you seen models like SD1.5/SD XL 1.0 using diffrax in any context? So I could see it and try to refactor in Automatic1111 sd webui?

torchsde is used upstream in [k-diffusers and ](https://github.com/crowsonkb/k-diffusion) as well as in [diffusers](https://github.com/huggingface/diffusers) - and pretty much ALL sd implementations are using first (if you're using original ldm pipeline) or the second (if you're using diffusers pipeline) for samplers implementations.

as such, pretty much NO application can refactor to switch away from `torchsde`. and when i say that, i mean 99% of sd install base as i'm sure there is somewhere something that uses `diffrax`

**Comment by lxuechen** [comment]
Given the discussions here, I'll try my best to find a few hours this weekend to patch the issues here, if they have not been fixed by then.

**Comment by akx** [comment]
@vladmandic #140 was merged, so please rebase? :)

**Comment by vladmandic** [comment]
> @vladmandic #140 was merged, so please rebase? :)

done!

**Review by patrick-kidger — APPROVED** [review]

**Comment by vladmandic** [comment]
great stuff - now only for `pypi` push/refresh :)

**Comment by patrick-kidger** [comment]
Hurrah! I've just merged and done a push to PyPI. Lmk how things go.

**Comment by lxuechen** [comment]
Thanks! @akx @vladmandic @patrick-kidger

**Comment by vladmandic** [comment]
> Hurrah! I've just merged and done a push to PyPI. Lmk how things go.

looks all good here!

**Pull request merged**
